### ISSUE TITLE
Backup and restore appmanifest file

### ISSUE THREAD

**Issue by ibillingsley** [kinsi55/BeatSaber_UpdateSkipper#14]
It would be nice if it created a backup of the appmanifest_620980.acf file before modifying it, and there could be a button to restore the backup.

That way, you could update the game by restoring the backup instead of verifying the integrity of game files. I've been doing this manually each update. Generally the normal update is a much smaller download than verify, because it only downloads deltas instead of whole files.

**Comment by kinsi55** [comment]
You could just manually insert the previous manifest id into the textbox instead of auto-retreiving it. I think for most users the process of such an option is going to be too complicated - Many people skip multiple consecutive updates because they have no reason to update in the first place in which case and it just becomes a mess when somebody restores to the wrong manifest id etc etc - Verifying game integrity is a one-stop solution that works, always.

**Comment by ibillingsley** [comment]
Fair enough, I didn't consider the complexity of skipping multiple updates.
