### ISSUE TITLE
Failed to retrieve manifest

### ISSUE THREAD

**Issue by sillyWillieBilly** [kinsi55/BeatSaber_UpdateSkipper#17]
Hello,

When i try to retrieve latest manifest automatically it fails. 
Latest release
![image](https://github.com/user-attachments/assets/5e9a39d3-1f3c-4da0-a7de-71ea85fc5298)

Clarification: manually pasting works ok

**Comment by kinsi55** [comment]
Seems like the old SteamKit Version (2.3.0) cannot connect to Steam anymore, just simply updating that didnt fix it, the Signature for `PICSGetProductInfo` changed and it now requires a `PICSRequest` rather than just the AppId - I tried to supply it via that but its still broken in that case. I'll have to have another look at some point but right now I'm clueless

**Comment by kinsi55** [comment]
Seems like this resolved itself on its own.
